# Generated by Django 3.2.9 on 2021-12-08 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('pred', models.NullBooleanField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 12, 8, 8, 48, 51, 316486))),
                ('is_delete', models.NullBooleanField(default=False)),
            ],
        ),
    ]
