# Generated by Django 3.2.9 on 2021-12-09 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operations', '0002_gendertest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderCNN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('pred', models.NullBooleanField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 12, 9, 4, 26, 39, 664954))),
                ('is_delete', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='GenderTest',
        ),
    ]
