# Generated by Django 3.2.9 on 2021-12-09 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operations', '0003_auto_20211209_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendercnn',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 7, 1, 50, 572182)),
        ),
        migrations.AlterField(
            model_name='gendercnn',
            name='image',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='gendercnn',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gendercnn',
            name='pred',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
