# Generated by Django 3.2.9 on 2021-12-09 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operations', '0005_auto_20211209_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender_cnn',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 12, 9, 10, 21, 8, 525525), max_length=60),
        ),
    ]
